export const navSections = [
  {
    label: 'Foundations',
    items: [
      { label: 'Typography', path: '/typography' },
      { label: 'Colors', path: '/colors' },
      { label: 'Spacing', path: '/spacing' },
      { label: 'Grid', path: '/grid' },
      { label: 'Shadows', path: '/shadows' },
      { label: 'Border Radius', path: '/border-radius' },
      { label: 'Icons', path: '/icons' },
    ],
  },
  {
    label: 'Components',
    items: [
      { label: 'Button', path: '/button' },
      { label: 'Icon Button', path: '/icon-button' },
      { label: 'Input', path: '/input' },
      { label: 'Textarea', path: '/textarea' },
      { label: 'Select', path: '/select' },
      { label: 'Checkbox', path: '/checkbox' },
      { label: 'Radio', path: '/radio' },
      { label: 'Toggle', path: '/toggle' },
      { label: 'Slider', path: '/slider' },
      { label: 'Badge', path: '/badge' },
      { label: 'Avatar', path: '/avatar' },
      { label: 'Tag', path: '/tag' },
      { label: 'Chip', path: '/chip' },
      { label: 'Tooltip', path: '/tooltip' },
      { label: 'Popover', path: '/popover' },
      { label: 'Dropdown', path: '/dropdown' },
      { label: 'Modal', path: '/modal' },
      { label: 'Drawer', path: '/drawer' },
      { label: 'Alert', path: '/alert' },
      { label: 'Toast', path: '/toast' },
      { label: 'Banner', path: '/banner' },
      { label: 'Card', path: '/card' },
      { label: 'Table', path: '/table' },
      { label: 'List', path: '/list' },
      { label: 'Tabs', path: '/tabs' },
      { label: 'Accordion', path: '/accordion' },
      { label: 'Navigation', path: '/navigation' },
      { label: 'Breadcrumb', path: '/breadcrumb' },
      { label: 'Pagination', path: '/pagination' },
      { label: 'Stepper', path: '/stepper' },
      { label: 'Progress', path: '/progress' },
      { label: 'Spinner', path: '/spinner' },
      { label: 'Skeleton', path: '/skeleton' },
      { label: 'Divider', path: '/divider' },
    ],
  },
  {
    label: 'Layouts',
    items: [
      { label: 'Container', path: '/container' },
      { label: 'Flexbox', path: '/flexbox' },
      { label: 'Grid Layout', path: '/grid-layout' },
      { label: 'Stack', path: '/stack' },
      { label: 'Sidebar Layout', path: '/sidebar-layout' },
      { label: 'Split Layout', path: '/split-layout' },
    ],
  },
  {
    label: 'Patterns',
    items: [
      { label: 'Page Layout', path: '/page-layout' },
      { label: 'Form Pattern', path: '/form-pattern' },
      { label: 'Login', path: '/login' },
      { label: 'Dashboard', path: '/dashboard' },
      { label: 'Data Table', path: '/data-table' },
      { label: 'Empty State', path: '/empty-state' },
      { label: 'Error State', path: '/error-state' },
    ],
  },
]
